# Generated by Django 2.2.22 on 2021-05-09 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('channel', models.CharField(choices=[('adcolony', 'adcolony'), ('apple_search_ads', 'apple_search_ads'), ('chartboost', 'chartboost'), ('facebook', 'facebook'), ('google', 'google'), ('unityads', 'unityads'), ('vungle', 'vungle')], max_length=30)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('GB', 'England'), ('US', 'USA')], max_length=30)),
                ('os', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], max_length=30)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('installs', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'statistics',
                'verbose_name_plural': 'statistics',
                'ordering': ('date',),
            },
        ),
        migrations.AddConstraint(
            model_name='statistics',
            constraint=models.UniqueConstraint(fields=('date', 'channel', 'country', 'os'), name='unique report entry'),
        ),
    ]
